## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: xenial
sudo: true
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
    - julia: nightly
addons:
  homebrew:
    packages:
      - gcc@6
  apt:
    packages:
    - libblas3
    - libc6
    - libgcc1
    - libgfortran3
    - libgmp10
    - libgsl2
    - liblapack3
    - libstdc++6
    - zlib1g
before_install:
  - export VERSION=6.0.1
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export SCIP_BINARY=SCIPOptSuite-$VERSION-Linux.deb; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export SCIP_BINARY=SCIPOptSuite-$VERSION-Darwin-no-Ipopt.sh; fi
  - wget http://scip.zib.de/download/release/$SCIP_BINARY
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i SCIPOptSuite-$VERSION-Linux.deb; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x $SCIP_BINARY && mkdir scip && ./$SCIP_BINARY --skip-license --prefix=$(pwd)/scip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export SCIPOPTDIR=$(pwd)/scip; fi
# Use default build script.
# script:
#   - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
jobs:
  include:
    - stage: "MINLPTests"
      julia: 1.0
      os: linux
      script:
        - julia --project=test/MINLPTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/MINLPTests --color=yes test/MINLPTests/run_minlptests.jl
after_success:
  # push coverage results to Codecov, Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("SCIP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(Coveralls.process_folder())'
