name = "SCIP"
uuid = "82193955-e24f-5292-bf16-6f2c5261a85f"
version = "0.10.0"

[deps]
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SCIP_jll = "e5ac4fe4-a920-5659-9bf8-f9f73e9e79ce"

[compat]
Ipopt_jll = "3.13.2"
MathOptInterface = "0.10.4"
SCIP_jll = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
